// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: A.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from A.proto</summary>
public static partial class AReflection {

  #region Descriptor
  /// <summary>File descriptor for A.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgdBLnByb3RvGgdCLnByb3RvIlQKCU1lc3NhZ2UyMRIaCgdGaWVsZDg3GAEg",
          "ASgOMgkuRW51bV82MjgSDwoHRmllbGQ2MhgCIAEoCSIaCghFbnVtXzI0NhIO",
          "CgpWQUxVRV84NjQzEAAqGgoIRW51bV82MjgSDgoKVkFMVUVfMzQ0NBAAUABi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::BReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Enum_628), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Message21), global::Message21.Parser, new[]{ "Field87", "Field62" }, null, new[]{ typeof(global::Message21.Types.Enum_246) }, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum Enum_628 {
  [pbr::OriginalName("VALUE_3444")] Value3444 = 0,
}

#endregion

#region Messages
public sealed partial class Message21 : pb::IMessage<Message21>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Message21> _parser = new pb::MessageParser<Message21>(() => new Message21());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Message21> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message21() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message21(Message21 other) : this() {
    field87_ = other.field87_;
    field62_ = other.field62_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Message21 Clone() {
    return new Message21(this);
  }

  /// <summary>Field number for the "Field87" field.</summary>
  public const int Field87FieldNumber = 1;
  private global::Enum_628 field87_ = global::Enum_628.Value3444;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Enum_628 Field87 {
    get { return field87_; }
    set {
      field87_ = value;
    }
  }

  /// <summary>Field number for the "Field62" field.</summary>
  public const int Field62FieldNumber = 2;
  private string field62_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Field62 {
    get { return field62_; }
    set {
      field62_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Message21);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Message21 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Field87 != other.Field87) return false;
    if (Field62 != other.Field62) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Field87 != global::Enum_628.Value3444) hash ^= Field87.GetHashCode();
    if (Field62.Length != 0) hash ^= Field62.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Field87 != global::Enum_628.Value3444) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Field87);
    }
    if (Field62.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Field62);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Field87 != global::Enum_628.Value3444) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Field87);
    }
    if (Field62.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Field62);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Field87 != global::Enum_628.Value3444) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Field87);
    }
    if (Field62.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Field62);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Message21 other) {
    if (other == null) {
      return;
    }
    if (other.Field87 != global::Enum_628.Value3444) {
      Field87 = other.Field87;
    }
    if (other.Field62.Length != 0) {
      Field62 = other.Field62;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Field87 = (global::Enum_628) input.ReadEnum();
          break;
        }
        case 18: {
          Field62 = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Field87 = (global::Enum_628) input.ReadEnum();
          break;
        }
        case 18: {
          Field62 = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Message21 message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Enum_246 {
      [pbr::OriginalName("VALUE_8643")] Value8643 = 0,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
