// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: B.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from B.proto</summary>
public static partial class BReflection {

  #region Descriptor
  /// <summary>File descriptor for B.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgdCLnByb3RvKhoKCEVudW1fMjY4Eg4KClZBTFVFXzI1NDUQAGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Enum_268), }, null, null));
  }
  #endregion

}
#region Enums
public enum Enum_268 {
  [pbr::OriginalName("VALUE_2545")] Value2545 = 0,
}

#endregion


#endregion Designer generated code
